<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Rate;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * MessageRepository constructor.
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new ClassMetadata(Rate::class));
    }

    public function getAllRatesWithoutTopRates(array $topRates){
        return $this
            ->createQueryBuilder('rate')
            ->where('rate.rateName not in (:topRates)')
            ->setParameter('topRates', $topRates)
            ->getQuery()
            ->getResult();
    }

    public function getTopRates(array $topRates){
        return $this
            ->createQueryBuilder('rate')
            ->where('rate.rateName in (:topRates)')
            ->setParameter('topRates', $topRates)
            ->getQuery()
            ->getResult();
    }
    public function insert(Rate $rate){

        try{

            $this->_em->persist($rate);
            $this->_em->flush();

            return true;
        }catch (\Exception $e){

            return $e;
        }
    }
}
