<?php

namespace App\Repository;
use App\Entity\ExchangeRate;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ExchangeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRateRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * MessageRepository constructor.
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new ClassMetadata(ExchangeRate::class));
    }

    public function insert(ExchangeRate $exchangeRate){

        try{

            $this->_em->persist($exchangeRate);
            $this->_em->flush();

            return true;
        }catch (\Exception $e){

            return false;
        }
    }
}
